[build]
  command = "npm run build"
  publish = "build"
  
[[plugins]]
  package = "@netlify/plugin-sitemap"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
    
[functions]
  directory = "netlify/functions"